
spring:
    profiles:
        active: '@spring.profiles.active@'
server:
    port: 5000
    maxHttpHeaderSize: 6553600 
app:
    datasource:
        jdbc-url: jdbc:postgresql://swe443-journalentries.cfrwarbl7jf8.us-east-1.rds.amazonaws.com:5432/entriesdb
        username: postgres  
        password: achiever 
        pool-size: 30     